#!/bin/bash
CGROUP=/sys/fs/cgroup

[ -d $CGROUP ] ||
	mkdir $CGROUP

mountpoint -q $CGROUP ||
	mount -n -t tmpfs -o uid=0,gid=0,mode=0755 cgroup $CGROUP || {
		echo "Could not make a tmpfs mount. Did you use --privileged?"
		exit 1
	}

if [ -d /sys/kernel/security ] && ! mountpoint -q /sys/kernel/security
then
    mount -t securityfs none /sys/kernel/security || {
        echo "Could not mount /sys/kernel/security."
        echo "AppArmor detection and --privileged mode might break."
    }
fi

dockerd &
(( timeout = 60 + SECONDS ))
until docker info >/dev/null 2>&1
do
	if (( SECONDS >= timeout )); then
		echo 'Timed out trying to connect to internal docker host.' >&2
		break
	fi
	sleep 1
done

apparmor_parser -q -r <<EOF
#include <tunables/global>
profile deny-write flags=(attach_disconnected) {
  #include <abstractions/base>
  file,
  network,
  deny /tmp/** w,
  capability,
}
EOF

docker run -td --rm --init --name ubuntu-one --security-opt apparmor=deny-write ubuntu
docker run -td --rm --init --name ubuntu-two --security-opt apparmor=deny-write ubuntu

[[ $1 ]] && exec "$@"
exec bash --login
