version: '3.9'
services:
  task2:
    image: docker
    init: true
    command: docker run --rm  --name kodekloud-master --privileged --init kodekloud tail -f /dev/null
    networks:
      - bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      restart_policy: 
        condition: none

networks:
  bridge:
    external: true
    name: bridge