version: '3.9'
services:
  task2:
    image: docker
    command: 
      - /bin/sh
      - -c
      - |
        echo "docker run -d --init --name ubuntu-one ubuntu; docker run -d --init --name ubuntu-two ubuntu" | docker run --rm --name kodekloud-master --privileged --init -i kodekloud
    #command: docker run --rm --name ubuntu-one --init ubuntu
    networks:
      - bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      restart_policy: 
        condition: none

networks:
  bridge:
    external: true
    name: bridge